import requests

"""
filtros=[{"id":"tipo-de-busqueda","name":"Tipo de búsqueda","mainFilter":true,"type":"radio",
"values":[{"id":1,"label":"Comprar","value":[1,2]}]},
{"id":"tipo-de-propiedad","name":"Tipo de propiedad","mainFilter":true,"type":"check",
"values":[{"id":2,"label":"Departamento","value":[2]}]},
{"id":"region","type":"select","name":"Región",
"values":[{"label":"Metropolitana","id":13,"value":[13]}]},
{"id":"comuna","type":"select","name":"Comuna",
"values":[{"label":"Santiago","id":339,"value":[339]}]},
{"type":"check","id":"estado","name":"Estado","values":[{"id":1,"label":"Nueva","value":[2]}]},
{"id":"dormitorios","type":"radio","name":"Dormitorios",
"values":[{"id":1,"value":[0,0],"label":"Studio"}]
{"type":"radio","id":"bannos","name":"Baños",
"values":[{"id":1,"label":"1 baño","value":[1,1]}]},
{"type":"radio","id":"precios","name":"Precios","hasFilterName":true,
"values":[{"id":2,"value":[146236041,219354060]}],
"label":"$","unit":"moneda"}
]

order=1
page=undefined

------------------------------------------------------------
Precio
hasta $ 146.236.040: [{"id":1,"value":[0,146236040]}]
$ 146.236.041 a $ 219.354.060: [{"id":2,"value":[146236041,219354060]}]
$ 219.354.061 a $ 365.590.100: [{"id":3,"value":[219354061,365590100]}]
$ 365.590.101 o mas: [{"id":4,"value":[365590101,"x"]}]
------------------------------------------------------------
Tipo de operacion
Compra: [{"id":1,"label":"Comprar","value":[1,2]}]
Compra nueva: [{"id":1,"label":"Nueva","value":[2]}
Compra usada: [{"id":2,"label":"Usada","value":[1]}]
Arrendar: [{"id":2,"label":"Arrendar","value":[3]}]}
------------------------------------------------------------
Tipo de propiedad
Casa: [{"id": 1, "label": "Casa", "value": [1]}]
Departamento: [{"id": 2, "label": "Departamento", "value": [2]}]
Oficina: [{"id": 3, "label": "Oficina", "value": [3]}]
Cité: [{"id": 4, "label": "Cité", "value": [1]}]
Conjunto habitacional: [{"id": 5, "label": "Conjunto habitacional", "value": [1]}]
Condominio: [{"id": 6, "label": "Condominio", "value": [1]}]
Loft: [{"id": 7, "label": "Loft", "value": [2]}]
Dúplex: [{"id": 8, "label": "Dúplex", "value": [2]}]
Planta Libre: [{"id": 11, "label": "Planta Libre", "value": [3]}]
Local Comercial: [{"id": 12, "label": "Local Comercial", "value": [4]}]
Local: [{"id": 13, "label": "Local", "value": [4]}]
Casa apta local comercial: [{"id": 14, "label": "Casa apta local comercial", "value": [4]}]
Casas Comerciales: [{"id": 15, "label": "Casas Comerciales", "value": [4]}]
Negocio: [{"id": 16, "label": "Negocio", "value": [4]}]
Terreno: [{"id": 17, "label": "Terreno", "value": [5]}]
Sitio: [{"id": 18, "label": "Sitio", "value": [5]}]
Loteo: [{"id": 19, "label": "Loteo", "value": [5]}]
Paño: [{"id": 20, "label": "Paño", "value": [5]}]
Terreno Construcción: [{"id": 21, "label": "Terreno Construcción", "value": [5]}]
Parcela: [{"id": 22, "label": "Parcela", "value": [6]}]
Quinta: [{"id": 23, "label": "Quinta", "value": [6]}]
Agrícola: [{"id": 24, "label": "Agrícola", "value": [7]}]
Predio: [{"id": 25, "label": "Predio", "value": [7]}]
Fundo: [{"id": 26, "label": "Fundo", "value": [7]}]
Campo: [{"id": 27, "label": "Campo", "value": [7]}]
Industrial: [{"id": 28, "label": "Industrial", "value": [8]}]
Galpón: [{"id": 32, "label": "Galpón", "value": [9]}]
Bodega: [{"id": 30, "label": "Bodega", "value": [9]}]
Almacén: [{"id": 31, "label": "Almacén", "value": [9]}]
Estacionamiento: [{"id": 33, "label": "Estacionamiento", "value": [10]}]
Parcela Vacacional: [{"id": 34, "label": "Parcela Vacacional", "value": [11]}]
Cabañas: [{"id": 35, "label": "Cabañas", "value": [11]}]
Hotel: [{"id": 36, "label": "Hotel", "value": [11]}]
Hostal: [{"id": 37, "label": "Hostal", "value": [11]}]
Lodge: [{"id": 38, "label": "Lodge", "value": [11]}]
Motel: [{"id": 39, "label": "Motel", "value": [11]}]
Sitio Comercial: [{"id": 40, "label": "Sitio Comercial", "value": [5]}]
Sitio Residencial: [{"id": 41, "label": "Sitio Residencial", "value": [5]}]
Sitio industrial: [{"id": 42, "label": "Sitio industrial", "value": [5]}]
Sitios Para Subdision: [{"id": 43, "label": "Sitios Para Subdision", "value": [5]}]
Turistica: [{"id": 44, "label": "Turistica", "value": [11]}]
Bungalow: [{"id": 45, "label": "Bungalow", "value": [1]}]
Terreno Industrial: [{"id": 46, "label": "Terreno Industrial", "value": [5]}]
------------------------------------------------------------
Dormitorios
Studio: [{"id":1,"value":[0,0],"label":"Studio"}]
1 Dormitorio: [{"id":2,"label":"1 dormitorio","value":[1,1]}]
2 Dormitorios: [{"id":3,"label":"2 dormitorios","value":[2,2]}]
3 Dormitorios: [{"id":4,"label":"3 dormitorios","value":[3,3]}]
4 Dormitorios: [{"id":5,"label":"4 o mas dormitorios","value":[4,"x"]}]
------------------------------------------------------------
Baños
1 Baños: [{"id":1,"label":"1 baños","value":[1,1]}]}
2 Baños: [{"id":2,"label":"2 baños","value":[2,2]}]}
3 Baños: [{"id":3,"label":"3 baños","value":[3,3]}]}
4 Baños: [{"id":4,"label":"4 o mas baños","value":[4,"x"]}]}
------------------------------------------------------------
Regiones
Tarapacá: [{"label":"Tarapacá","id":1,"value":[1]}]
Antofagasta: [{"label":"Antofagasta","id":2,"value":[2]}]
Atacama: [{"label":"Atacama","id":3,"value":[3]}]
Coquimbo: [{"label":"Coquimbo","id":4,"value":[4]}]
Valparaiso: [{"label":"Valparaiso","id":5,"value":[5]}]
Bernardo OHiggins: [{"label":"Bernardo OHiggins","id":6,"value":[6]}]
Maule: [{"label":"Maule","id":7,"value":[7]}]
Biobío: [{"label":"Biobío","id":8,"value":[8]}]
Araucanía: [{"label":"Araucanía","id":9,"value":[9]}]
Los Lagos: [{"label":"Los Lagos","id":10,"value":[10]}]
Aysén: [{"label":"Aysén","id":11,"value":[11]}]
Magallanes: [{"label":"Magallanes","id":12,"value":[12]}]
Metropolitana: [{"label":"Metropolitana","id":13,"value":[13]}]
Los Ríos: [{"label":"Los Ríos","id":14,"value":[14]}]
Arica y Parinacota: [{"label":"Arica y Parinacota","id":15,"value":[15]}]
Ñuble: [{"label":"Ñuble","id":16,"value":[16]}]
------------------------------------------------------------
Comunas
General Lagos: [{label: General Lagos, id: 1, value: [1]}]
Putre: [{label: Putre, id: 2, value: [2]}]
Arica: [{label: Arica, id: 3, value: [3]}]
Camarones: [{label: Camarones, id: 4, value: [4]}]
Huara: [{label: Huara, id: 5, value: [5]}]
Camiña: [{label: Camiña, id: 6, value: [6]}]
Colchane: [{label: Colchane, id: 7, value: [7]}]
Iquique: [{label: Iquique, id: 8, value: [8]}]
Pozo Almonte: [{label: Pozo Almonte, id: 9, value: [9]}]
Pica: [{label: Pica, id: 10, value: [10]}]
Tocopilla: [{label: Tocopilla, id: 11, value: [11]}]
María Elena: [{label: María Elena, id: 12, value: [12]}]
Calama: [{label: Calama, id: 13, value: [13]}]
Ollagüe: [{label: Ollagüe, id: 14, value: [14]}]
San Pedro de Atacama: [{label: San Pedro de Atacama, id: 15, value: [15]}]
Mejillones: [{label: Mejillones, id: 16, value: [16]}]
Sierra Gorda: [{label: Sierra Gorda, id: 17, value: [17]}]
Antofagasta: [{label: Antofagasta, id: 18, value: [18]}]
Taltal: [{label: Taltal, id: 19, value: [19]}]
Chañaral: [{label: Chañaral, id: 20, value: [20]}]
Diego de Almagro: [{label: Diego de Almagro, id: 21, value: [21]}]
Caldera: [{label: Caldera, id: 22, value: [22]}]
Copiapó: [{label: Copiapó, id: 23, value: [23]}]
Tierra Amarilla: [{label: Tierra Amarilla, id: 24, value: [24]}]
Huasco: [{label: Huasco, id: 25, value: [25]}]
Vallenar: [{label: Vallenar, id: 26, value: [26]}]
Freirina: [{label: Freirina, id: 27, value: [27]}]
Alto del Carmen: [{label: Alto del Carmen, id: 28, value: [28]}]
La Higuera: [{label: La Higuera, id: 29, value: [29]}]
Vicuña: [{label: Vicuña, id: 30, value: [30]}]
La Serena: [{label: La Serena, id: 31, value: [31]}]
Coquimbo: [{label: Coquimbo, id: 32, value: [32]}]
Andacollo: [{label: Andacollo, id: 33, value: [33]}]
Paihuano: [{label: Paihuano, id: 34, value: [34]}]
Ovalle: [{label: Ovalle, id: 35, value: [35]}]
Río Hurtado: [{label: Río Hurtado, id: 36, value: [36]}]
Punitaqui: [{label: Punitaqui, id: 37, value: [37]}]
Monte Patria: [{label: Monte Patria, id: 38, value: [38]}]
Combarbalá: [{label: Combarbalá, id: 39, value: [39]}]
Canela: [{label: Canela, id: 40, value: [40]}]
Illapel: [{label: Illapel, id: 41, value: [41]}]
Los Vilos: [{label: Los Vilos, id: 42, value: [42]}]
Salamanca: [{label: Salamanca, id: 43, value: [43]}]
Algarrobo: [{label: Algarrobo, id: 44, value: [44]}]
El Quisco: [{label: El Quisco, id: 45, value: [45]}]
El Tabo: [{label: El Tabo, id: 46, value: [46]}]
Cartagena: [{label: Cartagena, id: 47, value: [47]}]
San Antonio: [{label: San Antonio, id: 48, value: [48]}]
Santo Domingo: [{label: Santo Domingo, id: 49, value: [49]}]
Isla de Pascua: [{label: Isla de Pascua, id: 50, value: [50]}]
Petorca: [{label: Petorca, id: 51, value: [51]}]
La Ligua: [{label: La Ligua, id: 52, value: [52]}]
Cabildo: [{label: Cabildo, id: 53, value: [53]}]
Papudo: [{label: Papudo, id: 54, value: [54]}]
Zapallar: [{label: Zapallar, id: 55, value: [55]}]
Putaendo: [{label: Putaendo, id: 56, value: [56]}]
Catemu: [{label: Catemu, id: 57, value: [57]}]
San Felipe: [{label: San Felipe, id: 58, value: [58]}]
Santa María: [{label: Santa María, id: 59, value: [59]}]
Panquehue: [{label: Panquehue, id: 60, value: [60]}]
Llay-Llay: [{label: Llay-Llay, id: 61, value: [61]}]
Nogales: [{label: Nogales, id: 62, value: [62]}]
Calera: [{label: Calera, id: 63, value: [63]}]
La Cruz: [{label: La Cruz, id: 64, value: [64]}]
Quillota: [{label: Quillota, id: 65, value: [65]}]
Hijuelas: [{label: Hijuelas, id: 66, value: [66]}]
Limache: [{label: Limache, id: 67, value: [67]}]
Olmué: [{label: Olmué, id: 68, value: [68]}]
San Esteban: [{label: San Esteban, id: 69, value: [69]}]
Rinconada: [{label: Rinconada, id: 70, value: [70]}]
Calle Larga: [{label: Calle Larga, id: 71, value: [71]}]
Los Andes: [{label: Los Andes, id: 72, value: [72]}]
Puchuncaví: [{label: Puchuncaví, id: 73, value: [73]}]
Juan Fernández: [{label: Juan Fernández, id: 74, value: [74]}]
Quintero: [{label: Quintero, id: 75, value: [75]}]
Viña del Mar: [{label: Viña del Mar, id: 76, value: [76]}]
Villa Alemana: [{label: Villa Alemana, id: 77, value: [77]}]
Valparaíso: [{label: Valparaíso, id: 78, value: [78]}]
Quilpué: [{label: Quilpué, id: 79, value: [79]}]
Casablanca: [{label: Casablanca, id: 80, value: [80]}]
Concón: [{label: Concón, id: 81, value: [81]}]
San Francisco de Mostazal: [{label: San Francisco de Mostazal, id: 82, value: [82]}]
Graneros: [{label: Graneros, id: 83, value: [83]}]
Codegua: [{label: Codegua, id: 84, value: [84]}]
Rancagua: [{label: Rancagua, id: 85, value: [85]}]
Machalí: [{label: Machalí, id: 86, value: [86]}]
Las Cabras: [{label: Las Cabras, id: 87, value: [87]}]
Coltauco: [{label: Coltauco, id: 88, value: [88]}]
Doñihue: [{label: Doñihue, id: 89, value: [89]}]
Olivar: [{label: Olivar, id: 90, value: [90]}]
Coinco: [{label: Coinco, id: 91, value: [91]}]
Requínoa: [{label: Requínoa, id: 92, value: [92]}]
Peumo: [{label: Peumo, id: 93, value: [93]}]
Quinta de Tilcoco: [{label: Quinta de Tilcoco, id: 94, value: [94]}]
Pichidegua: [{label: Pichidegua, id: 95, value: [95]}]
San Vicente: [{label: San Vicente, id: 96, value: [96]}]
Malloa: [{label: Malloa, id: 97, value: [97]}]
Rengo: [{label: Rengo, id: 98, value: [98]}]
Navidad: [{label: Navidad, id: 99, value: [99]}]
Litueche: [{label: Litueche, id: 100, value: [100]}]
La Estrella: [{label: La Estrella, id: 101, value: [101]}]
Pichilemu: [{label: Pichilemu, id: 102, value: [102]}]
Marchigue: [{label: Marchigue, id: 103, value: [103]}]
Paredones: [{label: Paredones, id: 104, value: [104]}]
Peralillo: [{label: Peralillo, id: 105, value: [105]}]
Palmilla: [{label: Palmilla, id: 106, value: [106]}]
San Fernando: [{label: San Fernando, id: 107, value: [107]}]
Pumanque: [{label: Pumanque, id: 108, value: [108]}]
Santa Cruz: [{label: Santa Cruz, id: 109, value: [109]}]
Nancagua: [{label: Nancagua, id: 110, value: [110]}]
Placilla: [{label: Placilla, id: 111, value: [111]}]
Lolol: [{label: Lolol, id: 112, value: [112]}]
Chépica: [{label: Chépica, id: 113, value: [113]}]
Chimbarongo: [{label: Chimbarongo, id: 114, value: [114]}]
San Javier: [{label: San Javier, id: 115, value: [115]}]
Villa Alegre: [{label: Villa Alegre, id: 116, value: [116]}]
Yerbas Buenas: [{label: Yerbas Buenas, id: 117, value: [117]}]
Colbún: [{label: Colbún, id: 118, value: [118]}]
Linares: [{label: Linares, id: 119, value: [119]}]
Retiro: [{label: Retiro, id: 120, value: [120]}]
Longaví: [{label: Longaví, id: 121, value: [121]}]
Parral: [{label: Parral, id: 122, value: [122]}]
Teno: [{label: Teno, id: 123, value: [123]}]
Vichuquén: [{label: Vichuquén, id: 124, value: [124]}]
Hualañe: [{label: Hualañe, id: 125, value: [125]}]
Rauco: [{label: Rauco, id: 126, value: [126]}]
Curicó: [{label: Curicó, id: 127, value: [127]}]
Romeral: [{label: Romeral, id: 128, value: [128]}]
Licantén: [{label: Licantén, id: 129, value: [129]}]
Sagrada Familia: [{label: Sagrada Familia, id: 130, value: [130]}]
Molina: [{label: Molina, id: 131, value: [131]}]
Chanco: [{label: Chanco, id: 132, value: [132]}]
Cauquenes: [{label: Cauquenes, id: 133, value: [133]}]
Pelluhue: [{label: Pelluhue, id: 134, value: [134]}]
Curepto: [{label: Curepto, id: 135, value: [135]}]
Río Claro: [{label: Río Claro, id: 136, value: [136]}]
Constitución: [{label: Constitución, id: 137, value: [137]}]
Pencahue: [{label: Pencahue, id: 138, value: [138]}]
Talca: [{label: Talca, id: 139, value: [139]}]
Pelarco: [{label: Pelarco, id: 140, value: [140]}]
San Clemente: [{label: San Clemente, id: 141, value: [141]}]
Maule: [{label: Maule, id: 142, value: [142]}]
Empedrado: [{label: Empedrado, id: 143, value: [143]}]
San Rafael: [{label: San Rafael, id: 144, value: [144]}]
Arauco: [{label: Arauco, id: 145, value: [145]}]
Curanilahue: [{label: Curanilahue, id: 146, value: [146]}]
Lebu: [{label: Lebu, id: 147, value: [147]}]
Los Álamos: [{label: Los Álamos, id: 148, value: [148]}]
Cañete: [{label: Cañete, id: 149, value: [149]}]
Contulmo: [{label: Contulmo, id: 150, value: [150]}]
Tirúa: [{label: Tirúa, id: 151, value: [151]}]
Cobquecura: [{label: Cobquecura, id: 152, value: [152]}]
Quirihue: [{label: Quirihue, id: 153, value: [153]}]
Ninhue: [{label: Ninhue, id: 154, value: [154]}]
San Carlos: [{label: San Carlos, id: 155, value: [155]}]
Ñiquén: [{label: Ñiquén, id: 156, value: [156]}]
San Fabián: [{label: San Fabián, id: 157, value: [157]}]
San Nicolás: [{label: San Nicolás, id: 158, value: [158]}]
Trehuaco: [{label: Trehuaco, id: 159, value: [159]}]
Portezuelo: [{label: Portezuelo, id: 160, value: [160]}]
Chillán: [{label: Chillán, id: 161, value: [161]}]
Coihueco: [{label: Coihueco, id: 162, value: [162]}]
Coelemu: [{label: Coelemu, id: 163, value: [163]}]
Ranquil: [{label: Ranquil, id: 164, value: [164]}]
Pinto: [{label: Pinto, id: 165, value: [165]}]
Quillón: [{label: Quillón, id: 166, value: [166]}]
Bulnes: [{label: Bulnes, id: 167, value: [167]}]
San Ignacio: [{label: San Ignacio, id: 168, value: [168]}]
El Carmen: [{label: El Carmen, id: 169, value: [169]}]
Pemuco: [{label: Pemuco, id: 170, value: [170]}]
Yungay: [{label: Yungay, id: 171, value: [171]}]
Chillán Viejo: [{label: Chillán Viejo, id: 172, value: [172]}]
San Rosendo: [{label: San Rosendo, id: 173, value: [173]}]
Yumbel: [{label: Yumbel, id: 174, value: [174]}]
Cabrero: [{label: Cabrero, id: 175, value: [175]}]
Laja: [{label: Laja, id: 176, value: [176]}]
Los Ángeles: [{label: Los Ángeles, id: 177, value: [177]}]
Tucapel: [{label: Tucapel, id: 178, value: [178]}]
Antuco: [{label: Antuco, id: 179, value: [179]}]
Quilleco: [{label: Quilleco, id: 180, value: [180]}]
Nacimiento: [{label: Nacimiento, id: 181, value: [181]}]
Negrete: [{label: Negrete, id: 182, value: [182]}]
Mulchén: [{label: Mulchén, id: 183, value: [183]}]
Santa Bárbara: [{label: Santa Bárbara, id: 184, value: [184]}]
Quilaco: [{label: Quilaco, id: 185, value: [185]}]
Tomé: [{label: Tomé, id: 186, value: [186]}]
Talcahuano: [{label: Talcahuano, id: 187, value: [187]}]
Penco: [{label: Penco, id: 188, value: [188]}]
Florida: [{label: Florida, id: 189, value: [189]}]
Concepción: [{label: Concepción, id: 190, value: [190]}]
Coronel: [{label: Coronel, id: 191, value: [191]}]
Hualqui: [{label: Hualqui, id: 192, value: [192]}]
Lota: [{label: Lota, id: 193, value: [193]}]
Santa Juana: [{label: Santa Juana, id: 194, value: [194]}]
San Pedro de la Paz: [{label: San Pedro de la Paz, id: 195, value: [195]}]
Chiguayante: [{label: Chiguayante, id: 196, value: [196]}]
Angol: [{label: Angol, id: 197, value: [197]}]
Renaico: [{label: Renaico, id: 198, value: [198]}]
Collipulli: [{label: Collipulli, id: 199, value: [199]}]
Purén: [{label: Purén, id: 200, value: [200]}]
Los Sauces: [{label: Los Sauces, id: 201, value: [201]}]
Ercilla: [{label: Ercilla, id: 202, value: [202]}]
Lonquimay: [{label: Lonquimay, id: 203, value: [203]}]
Lumaco: [{label: Lumaco, id: 204, value: [204]}]
Traiguén: [{label: Traiguén, id: 205, value: [205]}]
Victoria: [{label: Victoria, id: 206, value: [206]}]
Curacautín: [{label: Curacautín, id: 207, value: [207]}]
Galvarino: [{label: Galvarino, id: 208, value: [208]}]
Perquenco: [{label: Perquenco, id: 209, value: [209]}]
Carahue: [{label: Carahue, id: 210, value: [210]}]
Nueva Imperial: [{label: Nueva Imperial, id: 211, value: [211]}]
Temuco: [{label: Temuco, id: 212, value: [212]}]
Lautaro: [{label: Lautaro, id: 213, value: [213]}]
Vilcún: [{label: Vilcún, id: 214, value: [214]}]
Melipeuco: [{label: Melipeuco, id: 215, value: [215]}]
Saavedra: [{label: Saavedra, id: 216, value: [216]}]
Teodoro Schmidt: [{label: Teodoro Schmidt, id: 217, value: [217]}]
Freire: [{label: Freire, id: 218, value: [218]}]
Cunco: [{label: Cunco, id: 219, value: [219]}]
Toltén: [{label: Toltén, id: 220, value: [220]}]
Pitrufquén: [{label: Pitrufquén, id: 221, value: [221]}]
Gorbea: [{label: Gorbea, id: 222, value: [222]}]
Loncoche: [{label: Loncoche, id: 223, value: [223]}]
Villarrica: [{label: Villarrica, id: 224, value: [224]}]
Pucón: [{label: Pucón, id: 225, value: [225]}]
Curarrehue: [{label: Curarrehue, id: 226, value: [226]}]
Padre las Casas: [{label: Padre las Casas, id: 227, value: [227]}]
Mariquina: [{label: Mariquina, id: 228, value: [228]}]
Lanco: [{label: Lanco, id: 229, value: [229]}]
Panguipulli: [{label: Panguipulli, id: 230, value: [230]}]
Máfil: [{label: Máfil, id: 231, value: [231]}]
Valdivia: [{label: Valdivia, id: 232, value: [232]}]
Los Lagos: [{label: Los Lagos, id: 233, value: [233]}]
Corral: [{label: Corral, id: 234, value: [234]}]
Paillaco: [{label: Paillaco, id: 235, value: [235]}]
Futrono: [{label: Futrono, id: 236, value: [236]}]
La Unión: [{label: La Unión, id: 237, value: [237]}]
Lago Ranco: [{label: Lago Ranco, id: 238, value: [238]}]
Río Bueno: [{label: Río Bueno, id: 239, value: [239]}]
San Juan de la Costa: [{label: San Juan de la Costa, id: 240, value: [240]}]
San Pablo: [{label: San Pablo, id: 241, value: [241]}]
Osorno: [{label: Osorno, id: 242, value: [242]}]
Puyehue: [{label: Puyehue, id: 243, value: [243]}]
Río Negro: [{label: Río Negro, id: 244, value: [244]}]
Puerto Octay: [{label: Puerto Octay, id: 245, value: [245]}]
Purranque: [{label: Purranque, id: 246, value: [246]}]
Fresia: [{label: Fresia, id: 247, value: [247]}]
Frutillar: [{label: Frutillar, id: 248, value: [248]}]
Puerto Varas: [{label: Puerto Varas, id: 249, value: [249]}]
Llanquihue: [{label: Llanquihue, id: 250, value: [250]}]
Los Muermos: [{label: Los Muermos, id: 251, value: [251]}]
Puerto Montt: [{label: Puerto Montt, id: 252, value: [252]}]
Cochamó: [{label: Cochamó, id: 253, value: [253]}]
Maullín: [{label: Maullín, id: 254, value: [254]}]
Calbuco: [{label: Calbuco, id: 255, value: [255]}]
Ancud: [{label: Ancud, id: 256, value: [256]}]
Quemchi: [{label: Quemchi, id: 257, value: [257]}]
Dalcahue: [{label: Dalcahue, id: 258, value: [258]}]
Castro: [{label: Castro, id: 259, value: [259]}]
Curaco de Vélez: [{label: Curaco de Vélez, id: 260, value: [260]}]
Quinchao: [{label: Quinchao, id: 261, value: [261]}]
Chonchi: [{label: Chonchi, id: 262, value: [262]}]
Puqueldón: [{label: Puqueldón, id: 263, value: [263]}]
Queilén: [{label: Queilén, id: 264, value: [264]}]
Quellón: [{label: Quellón, id: 265, value: [265]}]
Hualaihué: [{label: Hualaihué, id: 266, value: [266]}]
Chaitén: [{label: Chaitén, id: 267, value: [267]}]
Futaleufú: [{label: Futaleufú, id: 268, value: [268]}]
Palena: [{label: Palena, id: 269, value: [269]}]
Guaitecas: [{label: Guaitecas, id: 270, value: [270]}]
Cisnes: [{label: Cisnes, id: 271, value: [271]}]
Aysén: [{label: Aysén, id: 272, value: [272]}]
Lago Verde: [{label: Lago Verde, id: 273, value: [273]}]
Coyhaique: [{label: Coyhaique, id: 274, value: [274]}]
Río Ibañez: [{label: Río Ibañez, id: 275, value: [275]}]
Chile Chico: [{label: Chile Chico, id: 276, value: [276]}]
Cochrane: [{label: Cochrane, id: 277, value: [277]}]
Tortel: [{label: Tortel, id: 278, value: [278]}]
O`Higgins: [{label: O`Higgins, id: 279, value: [279]}]
Natales: [{label: Natales, id: 280, value: [280]}]
Torres del Paine: [{label: Torres del Paine, id: 281, value: [281]}]
Laguna Blanca: [{label: Laguna Blanca, id: 282, value: [282]}]
San Gregorio: [{label: San Gregorio, id: 283, value: [283]}]
Río Verde: [{label: Río Verde, id: 284, value: [284]}]
Punta Arenas: [{label: Punta Arenas, id: 285, value: [285]}]
Primavera: [{label: Primavera, id: 286, value: [286]}]
Porvenir: [{label: Porvenir, id: 287, value: [287]}]
Timaukel: [{label: Timaukel, id: 288, value: [288]}]
Cabo de Hornos: [{label: Cabo de Hornos, id: 289, value: [289]}]
Antártica: [{label: Antártica, id: 290, value: [290]}]
Til Til: [{label: Til Til, id: 291, value: [291]}]
Colina: [{label: Colina, id: 292, value: [292]}]
Lampa: [{label: Lampa, id: 293, value: [293]}]
San José de Maipo: [{label: San José de Maipo, id: 294, value: [294]}]
Puente Alto: [{label: Puente Alto, id: 295, value: [295]}]
Pirque: [{label: Pirque, id: 296, value: [296]}]
Curacaví: [{label: Curacaví, id: 297, value: [297]}]
María Pinto: [{label: María Pinto, id: 298, value: [298]}]
Melipilla: [{label: Melipilla, id: 299, value: [299]}]
San Pedro: [{label: San Pedro, id: 300, value: [300]}]
Alhue: [{label: Alhue, id: 301, value: [301]}]
Peñaflor: [{label: Peñaflor, id: 302, value: [302]}]
El Monte: [{label: El Monte, id: 303, value: [303]}]
Talagante: [{label: Talagante, id: 304, value: [304]}]
Isla de Maipo: [{label: Isla de Maipo, id: 305, value: [305]}]
Padre Hurtado: [{label: Padre Hurtado, id: 306, value: [306]}]
Calera de Tango: [{label: Calera de Tango, id: 307, value: [307]}]
San Bernardo: [{label: San Bernardo, id: 308, value: [308]}]
Buin: [{label: Buin, id: 309, value: [309]}]
Paine: [{label: Paine, id: 310, value: [310]}]
Lo Barnechea: [{label: Lo Barnechea, id: 311, value: [311]}]
Vitacura: [{label: Vitacura, id: 312, value: [312]}]
Las Condes: [{label: Las Condes, id: 313, value: [313]}]
La Reina: [{label: La Reina, id: 314, value: [314]}]
Peñalolén: [{label: Peñalolén, id: 315, value: [315]}]
La Florida: [{label: La Florida, id: 316, value: [316]}]
Pudahuel: [{label: Pudahuel, id: 317, value: [317]}]
Cerro Navia: [{label: Cerro Navia, id: 318, value: [318]}]
Lo Prado: [{label: Lo Prado, id: 319, value: [319]}]
Maipú: [{label: Maipú, id: 320, value: [320]}]
Cerrillos: [{label: Cerrillos, id: 321, value: [321]}]
Renca: [{label: Renca, id: 322, value: [322]}]
Quilicura: [{label: Quilicura, id: 323, value: [323]}]
Independencia: [{label: Independencia, id: 324, value: [324]}]
Recoleta: [{label: Recoleta, id: 325, value: [325]}]
Conchalí: [{label: Conchalí, id: 326, value: [326]}]
Huechuraba: [{label: Huechuraba, id: 327, value: [327]}]
Lo Espejo: [{label: Lo Espejo, id: 328, value: [328]}]
Pedro Aguirre Cerda: [{label: Pedro Aguirre Cerda, id: 329, value: [329]}]
La Cisterna: [{label: La Cisterna, id: 330, value: [330]}]
San Ramón: [{label: San Ramón, id: 331, value: [331]}]
La Granja: [{label: La Granja, id: 332, value: [332]}]
El Bosque: [{label: El Bosque, id: 333, value: [333]}]
La Pintana: [{label: La Pintana, id: 334, value: [334]}]
San Miguel: [{label: San Miguel, id: 335, value: [335]}]
Quinta Normal: [{label: Quinta Normal, id: 336, value: [336]}]
Providencia: [{label: Providencia, id: 337, value: [337]}]
Estación Central: [{label: Estación Central, id: 338, value: [338]}]
Santiago: [{label: Santiago, id: 339, value: [339]}]
Ñuñoa: [{label: Ñuñoa, id: 340, value: [340]}]
San Joaquín: [{label: San Joaquín, id: 341, value: [341]}]
Macul: [{label: Macul, id: 342, value: [342]}]
Alto Hospicio: [{label: Alto Hospicio, id: 343, value: [343]}]
Hualpén: [{label: Hualpén, id: 344, value: [344]}]
Valle Grande: [{label: Valle Grande, id: 345, value: [345]}]
Cholchol: [{label: Cholchol, id: 346, value: [346]}]
Alto Biobío: [{label: Alto Biobío, id: 347, value: [347]}]



"""